//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbC.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbC.Net.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator base transform may not be null.
        /// </summary>
        internal static string BaseTransformIsNull {
            get {
                return ResourceManager.GetString("BaseTransformIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data may not be null.
        /// </summary>
        internal static string DataDictionaryIsNull {
            get {
                return ResourceManager.GetString("DataDictionaryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex may not be null.
        /// </summary>
        internal static string ExceptionIsNull {
            get {
                return ResourceManager.GetString("ExceptionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaskCharacter may not be null (&apos;\0&apos;).
        /// </summary>
        internal static string MaskCharacterIsNull {
            get {
                return ResourceManager.GetString("MaskCharacterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messageTemplate may not be null, String.Empty or all whitespace characters.
        /// </summary>
        internal static string MessageTemplateIsEmpty {
            get {
                return ResourceManager.GetString("MessageTemplateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of sensitive value names may not be null.
        /// </summary>
        internal static string SensitiveValuesListIsNull {
            get {
                return ResourceManager.GetString("SensitiveValuesListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform keys collection is null.
        /// </summary>
        internal static string TransformKeysCollectonIsNull {
            get {
                return ResourceManager.GetString("TransformKeysCollectonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms dictionary is null.
        /// </summary>
        internal static string TransformsDictionaryIsNull {
            get {
                return ResourceManager.GetString("TransformsDictionaryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueMasker may not be null.
        /// </summary>
        internal static string ValueMaskerIsNull {
            get {
                return ResourceManager.GetString("ValueMaskerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value transform is null.
        /// </summary>
        internal static string ValueTransformIsNull {
            get {
                return ResourceManager.GetString("ValueTransformIsNull", resourceCulture);
            }
        }
    }
}
