//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbC.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbC.Net.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator base transform may not be null.
        /// </summary>
        internal static string BaseTransformIsNull {
            get {
                return ResourceManager.GetString("BaseTransformIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower bound may not be greater than upper bound.
        /// </summary>
        internal static string BetweenBoundsNotNormalized {
            get {
                return ResourceManager.GetString("BetweenBoundsNotNormalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check digit algorithm may not be null.
        /// </summary>
        internal static string CheckDigitAlgorithmIsNull {
            get {
                return ResourceManager.GetString("CheckDigitAlgorithmIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparer may not be null.
        /// </summary>
        internal static string ComparerIsNull {
            get {
                return ResourceManager.GetString("ComparerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant value may not be null.
        /// </summary>
        internal static string ConstantValueIsNull {
            get {
                return ResourceManager.GetString("ConstantValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data may not be null.
        /// </summary>
        internal static string DataDictionaryIsNull {
            get {
                return ResourceManager.GetString("DataDictionaryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Build method was previously invoked.
        /// </summary>
        internal static string ExceptionDataAlreadyBuilt {
            get {
                return ResourceManager.GetString("ExceptionDataAlreadyBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex may not be null.
        /// </summary>
        internal static string ExceptionIsNull {
            get {
                return ResourceManager.GetString("ExceptionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length may not be less than one.
        /// </summary>
        internal static string LengthIsLessThanOne {
            get {
                return ResourceManager.GetString("LengthIsLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask character may not be null (&apos;\0&apos;).
        /// </summary>
        internal static string MaskCharacterIsNull {
            get {
                return ResourceManager.GetString("MaskCharacterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLength may not be negative.
        /// </summary>
        internal static string MaxLengthIsNegative {
            get {
                return ResourceManager.GetString("MaxLengthIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template may not be null, String.Empty or all whitespace characters.
        /// </summary>
        internal static string MessageTemplateIsEmpty {
            get {
                return ResourceManager.GetString("MessageTemplateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinLength may not be negative.
        /// </summary>
        internal static string MinLengthIsNegative {
            get {
                return ResourceManager.GetString("MinLengthIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad character may not be null (&apos;\0&apos;).
        /// </summary>
        internal static string PadCharacterIsNull {
            get {
                return ResourceManager.GetString("PadCharacterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to search with a regular expression is null.
        /// </summary>
        internal static string RegexInputIsNull {
            get {
                return ResourceManager.GetString("RegexInputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex may not be null.
        /// </summary>
        internal static string RegexIsNull {
            get {
                return ResourceManager.GetString("RegexIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex text may not be null, String.Empty or all whitespace characters.
        /// </summary>
        internal static string RegexTextIsEmpty {
            get {
                return ResourceManager.GetString("RegexTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not a defined member of the RequirementType enumeration.
        /// </summary>
        internal static string RequirementTypeIsNotDefined {
            get {
                return ResourceManager.GetString("RequirementTypeIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of sensitive value names may not be null.
        /// </summary>
        internal static string SensitiveValuesListIsNull {
            get {
                return ResourceManager.GetString("SensitiveValuesListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target substring is null.
        /// </summary>
        internal static string TargetSubstringIsNull {
            get {
                return ResourceManager.GetString("TargetSubstringIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform keys collection may not be null.
        /// </summary>
        internal static string TransformKeysCollectonIsNull {
            get {
                return ResourceManager.GetString("TransformKeysCollectonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms dictionary may not be null.
        /// </summary>
        internal static string TransformsDictionaryIsNull {
            get {
                return ResourceManager.GetString("TransformsDictionaryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value transform may not be null.
        /// </summary>
        internal static string ValueTransformIsNull {
            get {
                return ResourceManager.GetString("ValueTransformIsNull", resourceCulture);
            }
        }
    }
}
